# Generated by Django 3.2.8 on 2022-06-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subirword', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoclausula',
            name='file',
            field=models.FileField(upload_to='clausula/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='archivoclausula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='archivoclausula',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre'),
        ),
    ]
