# Generated by Django 3.2.8 on 2022-06-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subirword', '0002_auto_20220628_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoClausula',
        ),
    ]
