# Generated by Django 3.2.8 on 2022-06-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subirword', '0004_archivoclausula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoclausula',
            name='file',
            field=models.FileField(upload_to='clausulas/'),
        ),
    ]
