# Generated by Django 3.2.8 on 2022-06-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clausulas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=100, null=True, verbose_name='Subtitulo')),
                ('numpoliza', models.CharField(max_length=50, null=True, verbose_name='Numero poliza')),
                ('asegurado', models.CharField(max_length=50, null=True, verbose_name='Asegurado')),
                ('texto', models.TextField(verbose_name='Parrafos')),
            ],
        ),
    ]
