# Generated by Django 3.2.8 on 2022-06-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarword', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clausulas',
            old_name='asegurado',
            new_name='nameaseg',
        ),
        migrations.RenameField(
            model_name='clausulas',
            old_name='subtitulo',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='clausulas',
            old_name='texto',
            new_name='textpoliza',
        ),
        migrations.RenameField(
            model_name='clausulas',
            old_name='titulo',
            new_name='title',
        ),
    ]
